export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  OLD_DEVICE_NOT_SCRAPPABLE: "OLD_DEVICE_NOT_SCRAPPABLE",
  NEW_DEVICE_ALREADY_PREOCCUPIED: "NEW_DEVICE_ALREADY_PREOCCUPIED",
  NEW_DEVICE_CODE_DUPLICATED: "NEW_DEVICE_CODE_DUPLICATED",
  REPLACEMENT_CONFLICT: "REPLACEMENT_CONFLICT",
  QR_ALREADY_BOUND: "QR_ALREADY_BOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_PENDING_REVIEW: "ORDER_PENDING_REVIEW",
  ORDER_NOT_PREOCCUPIED: "ORDER_NOT_PREOCCUPIED",
  RELATION_INCOMPLETE: "RELATION_INCOMPLETE"
} as const;
